# -*- coding: utf-8 -*-
"""Scania_APS_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9AWPrSN5HPM_vUB90ZPfOTl51__r6RJ
"""

import os
import glob
import shutil
import warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 30)

!wget -q "https://archive.ics.uci.edu/static/public/421/aps+failure+at+scania+trucks.zip" -O aps_failure.zip
!unzip -o -q aps_failure.zip -d aps_dataset

print("Downloaded files:")
for path in glob.glob("aps_dataset/**/*", recursive=True):
    if os.path.isfile(path):
        print(path)

training_matches = glob.glob(
    "aps_dataset/**/aps_failure_training_set.csv",
    recursive=True
)

if not training_matches:
    raise FileNotFoundError(
        "Training dataset could not be found."
    )

raw_file = training_matches[0]

os.makedirs("data/raw", exist_ok=True)
os.makedirs("data/cleaned", exist_ok=True)

raw_copy = "data/raw/aps_failure_training_set.csv"
shutil.copy2(raw_file, raw_copy)

print("Original file:", raw_file)
print("Preserved raw copy:", raw_copy)

df_raw = pd.read_csv(
    raw_file,
    skiprows=20,
    na_values=["na", "NA", "?"]
)

df = df_raw.copy()

original_rows, original_columns = df.shape

print("Original rows:", original_rows)
print("Original columns:", original_columns)

display(df.head())

original_column_names = df.columns.tolist()

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

print("First 15 cleaned column names:")
print(df.columns[:15].tolist())

print("DATASET INFORMATION")
print("-------------------")
print("Shape:", df.shape)
print("Total cells:", df.size)
print("Total missing values:", df.isna().sum().sum())
print("Exact duplicate rows:", df.duplicated().sum())

print("\nData-type counts:")
display(df.dtypes.value_counts())

print("\nClass distribution:")
display(df["class"].value_counts(dropna=False))

display(df.describe().T.head(20))

missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": (
        df.isna().mean() * 100
    ).round(2)
})

missing_summary = missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)

display(missing_summary.head(25))

top_missing = (
    missing_summary
    .head(20)
    .sort_values("missing_percentage")
)

plt.figure(figsize=(10, 7))

plt.barh(
    top_missing.index,
    top_missing["missing_percentage"]
)

plt.xlabel("Missing values (%)")
plt.ylabel("Feature")
plt.title("Top 20 Features by Missing-Value Percentage")
plt.grid(axis="x", alpha=0.3)
plt.show()

duplicates_before = df.duplicated().sum()

df = df.drop_duplicates().reset_index(drop=True)

duplicates_removed = (
    original_rows - len(df)
)

print("Duplicate rows identified:",
      duplicates_before)
print("Duplicate rows removed:",
      duplicates_removed)
print("Rows after duplicate removal:",
      len(df))

feature_columns = [
    column for column in df.columns
    if column != "class"
]

for column in feature_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

df["class"] = df["class"].astype("string")

print("Data-type counts after correction:")
display(df.dtypes.value_counts())

missing_threshold = 40

feature_missing_percentage = (
    df[feature_columns].isna().mean() * 100
)

high_missing_columns = (
    feature_missing_percentage[
        feature_missing_percentage >
        missing_threshold
    ]
    .index
    .tolist()
)

print("Columns removed for excessive missingness:",
      len(high_missing_columns))
print(high_missing_columns)

df = df.drop(columns=high_missing_columns)

feature_columns = [
    column for column in df.columns
    if column != "class"
]

constant_columns = [
    column
    for column in feature_columns
    if df[column].nunique(dropna=True) <= 1
]

print("Constant columns identified:",
      len(constant_columns))
print(constant_columns)

df = df.drop(columns=constant_columns)

feature_columns = [
    column for column in df.columns
    if column != "class"
]

missing_before_imputation = (
    df[feature_columns].isna().sum().sum()
)

median_values = df[feature_columns].median()

df[feature_columns] = (
    df[feature_columns]
    .fillna(median_values)
)

missing_after_imputation = (
    df[feature_columns].isna().sum().sum()
)

print("Missing values before imputation:",
      missing_before_imputation)
print("Missing values after imputation:",
      missing_after_imputation)

median_values.to_csv(
    "data/cleaned/imputation_medians.csv",
    header=["median"]
)

print("Classes before encoding:")
print(df["class"].value_counts())

df["class"] = df["class"].map({
    "neg": 0,
    "pos": 1
})

if df["class"].isna().any():
    raise ValueError(
        "Unexpected target-category value found."
    )

df["class"] = df["class"].astype("int8")

print("\nClasses after encoding:")
print(df["class"].value_counts())

feature_columns = [
    column for column in df.columns
    if column != "class"
]

q1 = df[feature_columns].quantile(0.25)
q3 = df[feature_columns].quantile(0.75)
iqr = q3 - q1

lower_limits = q1 - 1.5 * iqr
upper_limits = q3 + 1.5 * iqr

outlier_mask = (
    df[feature_columns].lt(
        lower_limits,
        axis=1
    ) |
    df[feature_columns].gt(
        upper_limits,
        axis=1
    )
)

outlier_counts = (
    outlier_mask
    .sum()
    .sort_values(ascending=False)
)

print("Top features by IQR outlier count:")
display(outlier_counts.head(20))

selected_features = (
    outlier_counts
    .head(10)
    .index
    .tolist()
)

plt.figure(figsize=(14, 6))

sns.boxplot(
    data=df[selected_features],
    orient="h"
)

plt.title("Features with the Highest Outlier Counts")
plt.xlabel("Observed value")
plt.show()

values_capped = int(outlier_mask.sum().sum())

df[feature_columns] = (
    df[feature_columns]
    .clip(
        lower=lower_limits,
        upper=upper_limits,
        axis=1
    )
)

print("Extreme values treated using IQR capping:",
      values_capped)
print("Rows deleted during outlier treatment: 0")

#Standardize numerical features

scaler = StandardScaler()

df[feature_columns] = scaler.fit_transform(
    df[feature_columns]
)

print("Numerical features standardized")

scaling_check = pd.DataFrame({
    "mean_after_scaling":
        df[feature_columns].mean(),
    "std_after_scaling":
        df[feature_columns].std()
})

display(scaling_check.head(15).round(3))

cleaned_rows, cleaned_columns = df.shape

remaining_constant_columns = [
    column
    for column in feature_columns
    if df[column].nunique(dropna=False) <= 1
]

print("FINAL DATA-QUALITY REPORT")
print("-------------------------")
print("Original dimensions:",
      (original_rows, original_columns))
print("Cleaned dimensions:",
      (cleaned_rows, cleaned_columns))
print("Rows removed:",
      original_rows - cleaned_rows)
print("Columns removed:",
      original_columns - cleaned_columns)
print("Remaining missing values:",
      df.isna().sum().sum())
print("Remaining duplicates:",
      df.duplicated().sum())
print("Remaining constant columns:",
      remaining_constant_columns)
print("Encoded target type:",
      df["class"].dtype)

print("\nFinal class distribution:")
display(df["class"].value_counts())

display(df.head())

cleaned_csv = (
    "data/cleaned/"
    "aps_failure_cleaned.csv"
)

df.to_csv(
    cleaned_csv,
    index=False,
    float_format="%.6f"
)

print("Saved:", cleaned_csv)

cleaning_summary = pd.DataFrame({
    "metric": [
        "Original rows",
        "Original columns",
        "Original missing values",
        "Duplicate rows removed",
        "High-missing columns removed",
        "Constant columns removed",
        "Missing values imputed",
        "Extreme values capped",
        "Final rows",
        "Final columns",
        "Final missing values",
        "Final duplicate rows"
    ],
    "value": [
        original_rows,
        original_columns,
        df_raw.isna().sum().sum(),
        duplicates_removed,
        len(high_missing_columns),
        len(constant_columns),
        missing_before_imputation,
        values_capped,
        cleaned_rows,
        cleaned_columns,
        df.isna().sum().sum(),
        df.duplicated().sum()
    ]
})

display(cleaning_summary)

cleaning_summary.to_csv(
    "data/cleaned/cleaning_summary.csv",
    index=False
)

from google.colab import files

files.download(raw_copy)
files.download(cleaned_csv)

files.download(
    "data/cleaned/cleaning_summary.csv"
)

median_values.to_csv(
    "imputation_medians.csv",
    header=["median"]
)

from google.colab import files
files.download("imputation_medians.csv")

scaler_parameters = pd.DataFrame({
    "feature": feature_columns,
    "mean": scaler.mean_,
    "scale": scaler.scale_
})

scaler_parameters.to_csv(
    "scaler_parameters.csv",
    index=False
)

files.download("scaler_parameters.csv")

import gzip
import shutil

with open(
    "/content/aps_dataset/aps_failure_training_set.csv",
    "rb"
) as source:
    with gzip.open(
        "aps_failure_training_set.csv.gz",
        "wb"
    ) as destination:
        shutil.copyfileobj(source, destination)

from google.colab import files
files.download("aps_failure_training_set.csv.gz")

import gzip
import shutil

with open(
    "/content/data/cleaned/aps_failure_cleaned.csv",
    "rb"
) as source:
    with gzip.open(
        "aps_failure_cleaned.csv.gz",
        "wb"
    ) as destination:
        shutil.copyfileobj(source, destination)

from google.colab import files
files.download("aps_failure_cleaned.csv.gz")